Add .NET 4.7 to NetFxExtension
wixtoolset/wix4-archive pull request #253
Opened 2017-10-18 15:23 UTC by joaoportela

Add .NET 4.7 installer for NetFxExtension.
Includes windows update for .NET 4.7 to work on windows 7.
Chose to use the web version of the windows update even for NetFx47Redist, because it is such an edge case and I didn't make to make the installer huge. Unfortunatelly, this will cause the installer to fail if there is no internet connection.

Based on the code from this issue: https://github.com/wixtoolset/issues/issues/5575
Hope this helps, any suggestions on improvements are welcome.

I'm not sure my wix code quality is acceptable as I have some code repetition.
I tested on some virtual machines to see if the windows update is triggered when it should.

2017-10-18 15:23 UTC, dnfclas commented
@__joaoportela__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla2.dotnetfoundation.org.

It will cover your contributions to all .NET Foundation-managed open source projects.
_Thanks,
.NET Foundation Pull Request Bot_

2017-10-18 15:25 UTC, dnfclas commented
__@joaoportela__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, .NET Foundation Pull Request Bot_

2017-12-28 13:45 UTC, joaoportela commented
Hi again!
What's preventing this from being merged? Is it anything that I can fix?

2019-05-16 20:58 UTC, markjourdan commented
@joaportela, I quickly glanced at your code and it looks like you still have references to 4.6.2. You just need a few more modifications till your code is complete.

**Example**
_you need to change WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED to be WIX_IS_NETFRAMEWORK_47_OR_LATER_INSTALLED_

`<Property Id="WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED" Secure="yes" />
    <SetProperty Id="WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED" Value="1" After="AppSearch">
      WIXNETFX4RELEASEINSTALLED >= "#$(var.NetFx462MinRelease)"
    </SetProperty>`

2019-05-16 21:00 UTC, markjourdan requested changes
You still reference: WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED. This needs to be fixed

2019-05-16 21:03 UTC, markjourdan requested changes
Just a few changes to complete the code.

2019-05-16 21:03 UTC, markjourdan commented on src/ext/NetFxExtension/wixlib/NetFx47.wxs
> +    <Property Id="WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED" Secure="yes" />
This needs to be changed:
```suggestion
    <Property Id="WIX_IS_NETFRAMEWORK_47_OR_LATER_INSTALLED_" Secure="yes" />
```

2019-05-16 21:03 UTC, markjourdan commented on src/ext/NetFxExtension/wixlib/NetFx47.wxs
> +    <SetProperty Id="WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED" Value="1" After="AppSearch">
```suggestion
    <SetProperty Id="WIX_IS_NETFRAMEWORK_47_OR_LATER_INSTALLED" Value="1" After="AppSearch">
```

2019-05-16 21:03 UTC, markjourdan commented on src/ext/NetFxExtension/wixlib/NetFx47.wxs
> +      WIXNETFX4RELEASEINSTALLED >= "#$(var.NetFx462MinRelease)"
```suggestion
      WIXNETFX4RELEASEINSTALLED >= "#$(var.NetFx47MinRelease)"
```

2020-05-22 11:27 UTC, rseanhall commented
This is in the new micro repo at https://github.com/wixtoolset/Netfx.wixext.

2020-05-22 11:27 UTC, closed without merging